name: Pull request check

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v4
    - uses: action/setup-node@v3
      with:
        node-version: 20
        cach: npm
    - name: Install dependencies
      run: npm ci
    - name: run lint
      run: npm run lint
    - name: run lint types
      run: npm run lint:types
    - name: run test
      run: npm run test
