name: Pull request check

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4
      - uses: action/setup-node@v3
        with:
          node-version: 20.x.x
          cach: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run lint:types
      - run: npm run test
